return {
    "stikypiston/cheaty.nvim",
    dependencies = { "nvim-lua/plenary.nvim" },
    config = function()
        require("cheaty").setup({
            cheatsheet = {
                "## Modes",
                "",
                "i           insert mode (left of cursor)",
                "a           insert mode (right of cursor)",
                "I           insert mode (start of line)",
                "A           insert mode (end of line)",
                "v           visual mode",
                "R           replace mode",
                "Ctrl + c    escape to normal",
                "",
                "## Operators",
                "",
                "d   delete",
                "y   yank into register",
                "gq  text formatting",
                ">   shift right",
                "<   shift left",
                "",
                "## Basic Editing",
                "",
                "p   paste after cursor",
                "P   paste before cursor",
                "o   start a new line",
                "u   undo",
                "r   redo",
                ".   repeat the last action",
                "",
                "## Word and Text Motions",
                "",
                "w   word forward",
                "e   word forward (end of word)",
                "b   word backward",
                ")   sentence forward",
                "(   sentence backward",
                "}   paragraph forward",
                "{   paragraph backward",
                "]   section forward",
                "[   section backward",
                "",
                "## Document Navigation",
                "",
                "$       end of line",
                "0/^     start of line (first char)",
                "G       end of document",
                "gg      start of document",
                "M       middle of visible screen",
                "zz      center current line",
                "%       matching brace/bracket",
                "",
                "## Search",
                "",
                "/           search",
                "Shift + /   search from the top",
                "",
                "## Text Object Selection",
                "",
                "Can be used in visual mode or after an operator.",
                "",
                "## Buffers",
                "",
                "Ctrl + o    go to previous buffer, mark or search",
                "Ctrl + ^    go to previous buffer",
                "",
                "## Windows",
                "",
                "Ctrl + w    window leader",
                "hjkl        navigate windows",
                "q           close",
                "",
                "## Tabs",
                "",
                "T           move window to new tab",
                "g + t/T     next/previous tab",
            }
        })
    end,
}
