return {
    "stikypiston/cheaty.nvim",
    dependencies = { "nvim-lua/plenary.nvim" },
    config = function()
        require("cheaty").setup({
            cheatsheet = {
                "## Modes",
                "",
                "i           insert mode",
                "v           visual mode",
                "Ctrl + c    Escape to normal",
                "",
                "## Operators",
                "",
                "d   delete",
                "y   yank into register",
                "gq  text formatting",
                ">   shift right",
                "<   shift left",
                "",
                "## Word and text object motions",
                "",
                "w   word forward",
                "b   word backward",
                ")   sentence forward",
                "(   sentence backward",
                "}   paragraph forward",
                "{   paragraph backward",
                "]   section forward",
                "[   section backward",
                "",
                "## Text object selection",
                "",
                "Can be used in visual mode or after an operator.",
                "",
                "## Buffers",
                "",
                "Ctrl + o    Go to previous open buffer, mark or search",
                "Ctrl + ^    Go to previous open buffer",
                "",
                "## Windows",
                "",
                "Ctrl + w    window leader",
                "hjkl        navigate windows",
                "q           close",
                "",
                "## Tabs",
                "",
                "T           move window to new tab",
                "g + t/T     next/previous tab",
            }
        })
    end,
}
